### ISSUE TITLE
Reject invalid date format for meta:lastUpdated field

### ISSUE THREAD

**Issue by ratheesh-kr** [tech-by-design/polyglot-prime#465] opened 2024-09-11 12:38 UTC
In order to support incremental changes to FHIR validation while we wait for the IG to publish we can start by validating the date format for the meta:lastUpdated field. When a FHIR bundle is passed to the TechBD FHIR endpoint, payloads with an invalid date format should be rejected and not passed on to the NYeC validation endpoint.

Example error text in the validation response:

"severity": "error",
"code": "processing",
"details": {
"coding": [
{
"system": "http://hl7.org/fhir/java-core-messageId",
"code": "Type_Specific_Checks_DT_DateTime_Regex"
}
]
},
"diagnostics": "The instant ''2024-09-09' doesn't meet format requirements for instant)' is not valid (by regex)",
"location": [
"Bundle.entry[0].resource/Patient/cc6ce0d9-297d-4166-b264-f7e33db53b67/.meta.lastUpdated",
"Line[1] Col[490]"
]

Attached files include a positive test case without the date validation error as well as a negative test case which includes the value '2024-09-09' which is an invalid format. The value is found in the meta:lastUpdated field of the patient resource.

**Comment by ratheesh-kr** [comment] 2024-09-11 12:40
Added this ticket in [Help Desk Support](https://github.com/tech-by-design/help-desk-non-phi/issues/16).

**Comment by shah** [comment] 2024-09-11 18:23
This is a duplicate of #466 and will be rewritten more generically.

**Closed by shah** 2024-09-11 18:23 UTC
